# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Ian Varonin's Blog
description: Welcome to my blog
github_username: ivaronin
email: ivaronin@gmail.com
website: ianvaronin.com
author: Ian Varonin

# pageinate: 3

# # Email and twitter are optional:
# email: ivaronin@gmail.com
# twitter_username:

# Set this to true to get LaTeX math equation support
use_math:

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Everything below here can be ignored, unless you want to change the theme entirely
remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: Hacker-Blog
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/modernist@v0.2.0
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-remote-theme

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
